### ISSUE TITLE
Adopt netstandard

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/Akavache#308]

**Comment by khionu** [comment]
Very much looking forward to this x33 I have Akavache wrapped in a Cache Class that has been the cornerstone of my storage. Keep up the great work!!

**Comment by ghuntley** [comment]
Currently blocked by Splat which needs to upgrade to netstandard. Unit tests won't be testable until rxui7-master comes out due to depednancies.

**Comment by PhilippeTroller** [comment]
Hi, When do you plan to update Akavache to support netstatndard ?
I can't decently use the last version of Refit (by example) with Akavache.

**Comment by khionu** [comment]
> Currently blocked by Splat
Need to follow them for this.

**Comment by khionu** [comment]
Actually, this seems to be done https://github.com/paulcbetts/splat/pull/146

**Comment by fonix232** [comment]
@ghuntley Any update on this? Splat has supported netstandard since 5th November, and I'm pretty sure many are waiting for Akavache to do so too.

**Comment by ghuntley** [comment]
PRs welcome. I'm waiting for VS2017 to settle on down.

**Comment by ghuntley** [comment]
Note: RxUI V7 is not netstandard, we decided to hold off. Akavache still has dependency on RxUI going to netstandard which is scheduled for v8

**Comment by olevett** [comment]
@ghuntley happy to pick this up if you're happy with the state of RxUI now?

**Comment by roggan87** [comment]
Just chiming in that I'd *looove* this to happen. We're about to rewrite a project and this could be a deal breaker for us in the decision to choose Akavache or some other database... I'm definitely going to keep an eye on this issue :)

**Comment by PureWeen** [comment]
I made a first go at this. 
Pulled into one of my Android projects and it seems happy

https://github.com/PureWeen/Akavache/tree/netstandard

I haven't messed with the packaging yet and the test project seems to be based on SL which I'm guessing will need to change.   Also removed SilverLight and anything pre-UAP

**Comment by olevett** [comment]
Great work :)

Will try and get a proper look at it this weekend, but I've got a couple of first thoughts
- do we need the Akavache.Mobile project still? Might be a broader question than this PR/change, so kinda happy to just ignore
- The code in `Portable`  looks to be shared across all platforms - not sure it needs to be in the subdirectory at all?
- There are references to xamarin-mobile and xamarin-common in the csproj but only a xamarin-mobile folder - is there anything that actually needs xamarin-common?

**Comment by PureWeen** [comment]
> do we need the Akavache.Mobile project still? Might be a broader question than this PR/change, so kinda happy to just ignore

I had that thought while I was migrating it. I mean it's just like 25 lines of code that could probably just exist in a readme.  I use the concept of that project in my projects but just copied the code locally instead of using nuget. It averages 7 downloads a day on nuget.   Other votes yay or nay?

> The code in Portable looks to be shared across all platforms - not sure it needs to be in the subdirectory at all?

Agreed.  I had just left how it was intact but it doesn't really make any sense

> There are references to xamarin-mobile and xamarin-common in the csproj but only a xamarin-mobile folder - is there anything that actually needs xamarin-common?

Probably not. While converting I kept copying things into them and realizing they weren't the right places. I left them there for now just in case during additional edits they became relevant but it's not that hard to add back in if need be..  Most things seem to have a decent place. The only ones I feel weird about right now are files that work for everyone except UWP
https://github.com/PureWeen/Akavache/blob/netstandard/src/Akavache/Platforms/shared/SimpleFilesystemProvider.cs

Is it worth adding a SharedButNotUwp folder? I'd say probably or some version of that. It's nice having the folders representing the files accurately.

The other UWP outlier is
https://github.com/PureWeen/Akavache/blob/netstandard/src/Akavache/Platforms/shared/MD5Managed.cs

where UWP has a slightly different implementation of the MD5 base. So I need to vet if that's ok.

On a side note the cake file updates to RxUI all make sense so I'll just use that as guidance for updating the cake file sometime next week.

**Comment by PureWeen** [comment]
Alright I checked in a cake file 
https://github.com/PureWeen/Akavache/blob/netstandard/build.cake

I added an empty project to do the packing for the Akavache package in the same way the current one works
https://github.com/PureWeen/Akavache/blob/netstandard/src/AkavachePkg/AkavachePkg.csproj

That seems to be what's recommended for it

Let me know if there are additional steps I can help with. I pulled this with the latest React bits as well into a few local apps i have and all seemed right with the world

**Comment by olevett** [comment]
Couple of things, but looking good so think it's probably worth PR-ing at this point (these get increasingly minor/trivial :))
- Probably worth merging and then tidying up any loose ends (e.g. the SharedNotUWP)
- I'd be keen to either drop the separate project for SQLite (e.g. just ship a single akavache package) or at least rename the csprojs to match the nuget names (Akavache.Core which includes the code and Akavache which is the wrapper project), as I think it'll make it a bit easier to follow.
- Given there are 5 projects, might be easier to have them all in the solution root rather than in Solution Folders
- There's a project reference to `Directory.build.props` and `MakeRelease.ps1` but I don't think either of these files exist
- Whilst this is referencing the pre-release RxUI packages, a [Nuget.config](https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file) file referencing the myget feed would be helpful

**Comment by PureWeen** [comment]
Cool!!!
The ReactiveUI reference made it all a pretty paint by numbers operations :-) so thanks for that everyone involved

> Probably worth merging and then tidying up any loose ends (e.g. the SharedNotUWP)

I'll make a few more changes based on these comments and PR this weekend or early next week

> I'd be keen to either drop the separate project for SQLite (e.g. just ship a single akavache package) or at least rename the csprojs to match the nuget names (Akavache.Core which includes the code and Akavache which is the wrapper project), as I think it'll make it a bit easier to follow.

Yea I wasn't sure the exact motivation so I just left it intact but as it stands it is just a proxy to the SQLLite project so not sure what's gained? Maybe someone else can chime in as to the original intent?  I feel like Akavache.SQLLite  should just become Akavache  and Akavache should just become Akavache.core

> Given there are 5 projects, might be easier to have them all in the solution root rather than in Solution Folders

sounds good

> There's a project reference to Directory.build.props and MakeRelease.ps1 but I don't think either of these files exist

For some reason I had the **Directory.build.props** file in the wrong folder outside of the solution folder which is why it wasn't coming along for the ride. I've modified and checked that in. Also removed MakeRelease.ps1

> Whilst this is referencing the pre-release RxUI packages, a Nuget.config file referencing the myget feed would be helpful

will do

**Comment by PureWeen** [comment]
Alright made changes around suggestions and created this

https://github.com/akavache/Akavache/pull/367

**Comment by khionu** [comment]
This can be closed now, I believe?
