### ISSUE TITLE
Akavache 5.0 + Microsoft Mobile Services 0.15 = Conflict

### ISSUE THREAD

**Issue by biapar** [reactiveui/Akavache#382]
Hi,
I reported a similar problem like this https://github.com/akavache/Akavache/issues/332 .
If we use Akavache 5.0 and Mobile Services 0.15, we have some problem and background crash on SQL lib. Mobile Services don't work like it's not possible to access local data without to restart the application.

iOS[25645]: [MobileCenter] ERROR: -[MSDBStorage executeNonSelectionQuery:]/104 Failed to open database for non-selection query with result: 14.

After uninstall Akavache, Mobile Services work again and the app is stable.

**Comment by PureWeen** [comment]
If you do something like this

https://github.com/ericsink/SQLitePCL.raw/wiki/Using-multiple-libraries-that-use-SQLitePCL.raw

Does that fix the issue?

**Comment by jaelim-ms** [comment]
Did you start MobileCenter before Akavache initialization?

**Comment by biapar** [comment]
Yes. I put the init code in the start function before akavache init.

**Comment by PureWeen** [comment]
Did you try to freeze the provider during init so the bundle stays consistent?

**Comment by jaelim-ms** [comment]
@biapar, you are mentioning `background crash on SQL lib`, MobileCenter shouldn't crash the application by any reasons. Can you provide me how you are initializing both libraries?

**Comment by ghuntley** [comment]
Some updates over at https://github.com/Microsoft/mobile-center-sdk-dotnet/issues/439#issuecomment-332055951

- Azure Mobile Centre is actually developed as objective-c first; then that library is bundled up into an assembly w/p/invoke headers/bindings. See https://github.com/Microsoft/mobile-center-sdk-ios/tree/develop/MobileCenter/MobileCenter
- There's no easy way out of this situation; the only way out of this hot mess would be if the entire .NET  ecosystem started using and standardized on `bundle_green` (i.e. don't ship sqlite for ios) but that still wouldn't fix consumers who use sqlite encryption or couchbase lite.

+cc @ericsink

**Comment by ericsink** [comment]
Ah, that summary is helpful, as I did not realize Azure Mobile Center was built that way.

As you say, there is no easy solution here that will prevent the problem, but unless I am missing something, I do think individual instances of the problem can be handled with extra init logic.  

In the general case, when something else is insisting on a specific instance of sqlite, we just need to make sure that SQLitePCL.raw is talking to that same instance.  In this case, yes, it means tricking Akavache to use bundle_green instead of e_sqlite3.

And yes, as I usually say in these situations, if everybody standardized on bundle_green, then we would simply be trading away one set of problems and receiving another.  I have yet to see a set of problems that looks dramatically more appealing than the set we have now.  :-)

That said, I've been starting some early work on what I would call version 2.0 of SQLitePCL.raw, and I do regard this as an opportunity to think once again about these issues.

**Comment by biapar** [comment]
@jaelim-ms here is the code: https://github.com/Microsoft/mobile-center-sdk-dotnet/issues/439

**Comment by PureWeen** [comment]
I put this together

https://github.com/PureWeen/Akavache.Samples/tree/azuremobile

I don't know a huge amount about Mobile Center so maybe I'm not doing the right things to trigger the exception properly but everything seems to startup and Akavache seems to run happily.

I basically just copied the startup code out of the Contoso samples in the Mobile center sdk

This is using the latest 6.0 Netstandard bits as well so maybe that has something to do with it

**Comment by tofutim** [comment]
I have a customized bundle of SQLitePCLRaw. Is there a way I can use akavache without making a customized build of akavache?

**Comment by ericsink** [comment]
@tofutim I suppose that depends on what customizations you have done and what version of SQLitePCL.raw you started with.  If you have FreezeProvider in your build, you can probably use that.

**Comment by EmilAlipiev** [comment]
i think that this can be closed. Microsoft Mobile Services is deprecated and akavache has newer version

**Comment by glennawatson** [comment]
Closing due to Microsoft Mobile Services being deprecated.
