### ISSUE TITLE
Akavache Memory Leak? 

### ISSUE THREAD

**Issue by EmilAlipiev** [reactiveui/Akavache#398]
I am using version 5.0.0 and experiencing high amount of memory usage. when I profile what is causing this. I am seeing always akavache prints on top. just like images below. what might cause this issue? Is it that somehow connection left option and i need to dispose something?

I am simply using GetObject function. 

  var result = await BlobCache.UserAccount.GetObject<T>(key);

![image](https://user-images.githubusercontent.com/10422347/33841364-d20eabaa-de97-11e7-9777-6c05c6b22ead.png)

![image](https://user-images.githubusercontent.com/10422347/33841403-edb32ebc-de97-11e7-9ec2-bd008b027be7.png)

**Comment by PureWeen** [comment]
Do you see this as an ever growing thing? or is this just after one initial run? 

Like if you call this every 5 seconds or so and let the app run for a minute do you see an ever increasing amount of allocations?   

I mainly ask because I do a lot of reads and writes into Akavache (every 5 to 10 seconds) over hours of use and when I've profiled my app through Xam Profiler I don't see an increase in memory usage between snap shots

Sometimes if you take a snap shot while an operation is happening it will also make it look like some memory is left over because the memory is just still allocated somewhere and the operation hasn't finished. Like if you take a snap shot in the middle of a web call or something of that nature

**Comment by EmilAlipiev** [comment]
@PureWeen  I have an increase in my memory but it is difficult to say that it is caused by akavache or other stuff. Xam Profiler is quite difficult to use I found although I have a lot of good experience with VS profiler itself.

Anyhow, i want to indicate something here. This screenshot is taken from actions during OnStart of the app where I fetch data from my webservice and save them into akavache cache. every request, I am using, it increases my memory usage. I am not doing memory cache so why would these data or calls makes big difference. if I remove these calls, Memory usage drops to 50%. Beside that I dont understand why these in the screenshot shown as "Live"- green icon. In sqlite I would just insert and close connection, is it not automatically happening with akavache? my usage is basic like 
  protected async override void OnStart()
        {
     Akavache.BlobCache.ApplicationName = "myApp";

// do webservice call get the data and 
     var result = await BlobCache.UserAccount.InsertObject(key, data);
  }

and in my mainpage OnAppearing

     var data= await BlobCache.UserAccount.GetObject(key);      
  Bind data to Listview
