### ISSUE TITLE
What the differences between Akavache and Akavache.mobile

### ISSUE THREAD

**Issue by vkhadyka** [reactiveui/Akavache#444]
I realized that Nuget contains 2 package: Akavache and Akavache.mobile what a difference between them and what should I use for Xamarin mobile application?

**Comment by PureWeen** [comment]
@vkhadyka   Honestly I think Akavache.Mobile is a bit excessive and I personally wouldn't recommend using it. It adds another DLL to your project which can affect load time on Android. 

If you look at it all it is is two files
https://github.com/reactiveui/Akavache/tree/master/src/Akavache.Mobile

Basically it provides an Akavache implementation for  https://github.com/reactiveui/ReactiveUI/blob/4a7b6c7cb35efe4e936b6779e2ad60964894e1d0/src/ReactiveUI/Interfaces/ISuspensionDriver.cs

So if you're utilizing the Suspension Driver parts of ReactiveUI and you want to persist something about your application between when the app is suspended and then resumed that's where it is used. 

But typically I've just provided my own implementation of ISuspensionDriver or just copied the file over from Akavache.Mobile because I don't want to install a whole package and add an extra dll for one file
