### ISSUE TITLE
[BUG] Akavache > 6.0.0 alpha and MS AppCenter sqlite issues

### ISSUE THREAD

**Issue by bmacombe** [reactiveui/Akavache#502]
**Describe the bug**
When ever I try to update to later versions of Akavache and sqlite, I get runtime conflicts with MS App Center.

I've already read and tried the suggestions in the following without success.  Akavache does seem to work, but appcenter always errors that it can't open it's database.

#382 
https://github.com/ericsink/SQLitePCL.raw/wiki/Using-multiple-libraries-that-use-SQLitePCL.raw
https://github.com/PureWeen/Akavache.Samples/tree/azuremobile/MobileCenterApp

**Environment**

- OS:       XF 4.x, iOS, UWP, Android

**Additional context**

I don't suspect there is actually a bug in Akavache, mainly looking for any advice on making Akavache and appcenter play well together so I get get them update.  Right now I have to keep Akavache on 6.0.0-alpha and sqlite on 1.1.11 to avoid issues.

Thanks in advance!

**Comment by bmacombe** [comment]
I contributed, but I don't appear to have rights to add a label to the issue.

Thanks!

**Comment by ericsink** [comment]
SQLitePCLRaw 2.0 was released quite recently, and contains some breaking changes.  Lots of packages use SQLitePCLRaw, but not many of them have updated to 2.0 yet.  Akavache has, but AppCenter has not.


See ericsink/SQLitePCL.raw#288

Anyway, I *think* this is probably the source of the difficulty are seeing.  For now, you would need to stay with a slightly older version of Akavache in order to stay in SQLitePCLRaw 1.x because that's what AppCenter still wants.  In time, I hope to get everybody moved over to 2.0 so these kinds of issues can go away.

I hope this makes sense.

**Comment by bmacombe** [comment]
Thanks!, yes it does and I thought I tried that.  But I will try it again because I was doing so many things I could have gotten something all messed up.

My thought was to use Sqllite 1.1.8 and then the max version of Akavache that still supports it.  I will attempt again.

**Comment by bmacombe** [comment]
I finally was able to get Akavache 6.5.1 and AppCenter 2.5 to play nicely in my XF UWP project.  Thanks again for the advice!  I'll keep an eye out for AppCenter supporting V2 before updating to later Akavache builds.
