### ISSUE TITLE
[BUG] CS7069 when used alongside Splat or Splat.Drawing >= 9.0.4

### ISSUE THREAD

**Issue by john-manktelow** [reactiveui/Akavache#512]
**Describe the bug**

If a project references Splat (or Splat.Drawing) >=9.0.4, alongside Akavache 6.8.1, the compiler raises:

      Program.cs(10, 13): [CS7069] Reference to type 'IBitmap' claims it is defined in 'Splat', but it could not be found

**Steps To Reproduce**

This .csproj
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="akavache" Version="6.8.1" />
      <PackageReference Include="Splat" Version="9.0.5" />
    </ItemGroup>
</Project>

```

and this usage

```
using Akavache;

namespace Repro
{
    public class SomeClass
    {
        public void SomeMethod()
        {
            // Ask Akavache to do something with IBitmap
            var _ = BlobCache.InMemory.LoadImage("someKey");
        }
    }
}
```

Is enough to trigger it.

**Additional context**

This could probably be worked around with packages.config and dependencyVersion=Highest but that isn't an option with packagereferences.

Presumably we need a new release that is aware of the Splat/Splat.Drawing split in 9.0.4?

**Comment by glennawatson** [comment]
We will schedule for the near future to upgrade Akavache to Splat 9, this should resolve these issues.

**Comment by paul-charlton** [comment]
@glennawatson Do you have any rough idea of timescales?

I'm holding off updating ReactiveUI (as it updates splat) as I get a odd error which only happens when I try to build in AppStore mode, fine in Debug.

The error, if anyone is interested, is:
7>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error MT2101: Can't resolve the reference 'Splat.IBitmap', referenced from the method 'System.IObservable`1<Splat.IBitmap> Akavache.BitmapImageMixin/<>c__DisplayClass0_0::<LoadImage>b__0(System.Byte[])' in 'Splat, Version=8.3.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by glennawatson** [comment]
Nah. It's when I get time realistically since I am backed up with real life work for the next couple weeks. Happy to take a pr though to update it.

**Comment by paul-charlton** [comment]
i hear that, there seems to be a failed one there already?
https://github.com/reactiveui/Akavache/pull/513

if I get a chance I'll try

**Comment by glennawatson** [comment]
Ah that one is auto generated. Essentially there would need to be added a reference to splat.drawing I think that should solve the problems.
