### ISSUE TITLE
Kindly provide proper documentation and sample for xamarin.forms

### ISSUE THREAD

**Issue by swapnil591** [reactiveui/Akavache#533]

**Comment by glennawatson** [comment]
Doesn't follow template.

**Comment by glennawatson** [comment]
In future please don't be ignore the template of the issue. We have it setup for a very good reason so we are able to better diagnose issues that come in. The documentation applies to Xamarin Forms just as much as any other platform so because you didn't provide any information about what you found inadequate we have just closed the issue.
